#!/usr/bin/bash

set -euo pipefail

mutagen sync create --name=uno-bin-sync \
  ./bin/windows \
  milkwin2:'C:\Users\Admin\Desktop\workspace\uno-game-zhs' \
  -m one-way-safe \
  --permissions-mode=portable \
  -i "uno-server"
